version: '3'
services:
  server1:
    build: .
    image: server
    container_name: server1
    ports:
      - "5001:5000"
    environment:
      - ID=1
      - NUM_SERVERS=4
    volumes:
      - .:/usr/src/app
  server2:
    build: .
    image: server
    container_name: server2
    ports:
      - "5002:5000"
    environment:
      - ID=2
      - NUM_SERVERS=4
    volumes:
      - .:/usr/src/app
  server3:
    build: .
    image: server
    container_name: server3
    ports:
      - "5003:5000"
    environment:
      - ID=3
      - NUM_SERVERS=4
    volumes:
      - .:/usr/src/app
  server4:
    build: .
    image: server
    container_name: server4
    ports:
      - "5004:5000"
    environment:
      - ID=4
      - NUM_SERVERS=4
    volumes:
      - .:/usr/src/app
