version: '3'
services:
  server1:
    build: .
    image: server
    container_name: server1
    ports:
     - "5001:5000"
    volumes:
     - .:/server
  server2:
    build: .
    image: server
    container_name: server2
    ports:
     - "5002:5000"
    volumes:
     - .:/server
  server3:
    build: .
    image: server
    container_name: server3
    ports:
     - "5003:5000"
    volumes:
     - .:/server
  server4:
    build: .
    image: server
    container_name: server4
    ports:
     - "5004:5000"
    volumes:
     - .:/server

